### ISSUE TITLE
Improvements for auth project

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#15]
# Improvements for auth project

Improve the [auth](https://github.com/alxmedium/auth) project adding tools to enforce code quality, error detection and use code patterns to write better code.

## Checklist

- [x] The feature breaks the existing code base.
- [ ] Update a package version.
- [ ] Update a language version.
- [x] Update the **CircleCI** configuration.
- [ ] Update the **NPM scripts**.
- [ ] Update the **Makefile scripts**.
- [ ] Update the **Infrastructure**.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

- Use [wemake-python-styleguide](https://github.com/wemake-services/wemake-python-styleguide)
- Use [Codacy](https://www.codacy.com/)
- Use [Sentry](https://sentry.io/welcome/)
- Add **wemake-python-styleguide** to **CircleCI Workflows**
- Implement **SOLID** principles
