### ISSUE TITLE
Improvements for webapp project

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#16]
# Improvements for webapp project

Improve the [webapp](https://github.com/alxmedium/webapp) project adding tools to enforce code quality, error detection and use code patterns to write better code.

## Checklist

- [x] The feature breaks the existing code base.
- [ ] Update a package version.
- [x] Update a language version.
- [x] Update the **CircleCI** configuration.
- [x] Update the **NPM scripts**.
- [ ] Update the **Makefile scripts**.
- [ ] Update the **Infrastructure**.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

- Use [Codacy](https://www.codacy.com/)
- Use [Sentry](https://sentry.io/welcome/)
- Implement **SOLID** principles
- Rewrite all the code with **TypeScript**
- Use code base of **CRA**
- Wrap the `persistedReducers` into an immutable object
- Use **MUI** to improve the development time
- Finish the **Sagas** tests
