### ISSUE TITLE
Add Infrastructure

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#17]
# Add Infrastructure

Add Infrastructure as Code to connect to **AWS**

## Checklist

- [x] The feature breaks the existing code base.
- [x] Update a package version.
- [ ] Update a language version.
- [x] Update the **CircleCI** configuration.
- [x] Update the **NPM scripts**.
- [x] Update the **Makefile scripts**.
- [x] Update the **Infrastructure**.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

- Set up Vault
- Set up Ansible
- Set up AWS account for the project
- Create the **infrastructure** repository
