### ISSUE TITLE
Manage repositories milestones

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#20]
# New Feature Name

Manage the repositories milestones using the GitHub API

## Checklist

- [ ] The feature breaks the existing code base.
- [ ] Update a package version.
- [ ] Update a language version.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

Use the GitHub API to add, update, edit and delete the repository milestones, also to automatically add all the milestones to new repositories.
