### ISSUE TITLE
Update the information of the repositories

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#21]
# Update the README files

Update the **CircleCI** and Docker Hub** information in the **README** and **Docker** files

## Checklist

- [x] The feature breaks the existing code base.
- [x] Update a package version.
- [ ] Update a language version.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

Update the following files with the latest information of **CircleCI** and **Docker Hub**:

- *README*
- *Docker Compose*
