### ISSUE TITLE
Rename the Docker Hub Repositories

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#4]
## Rename the Docker Hub Repositories

Rename the name of the  **Docker Hub** repositories to standardize the names of the organization.

## Checklist

- [x] The feature breaks the existing code base.
- [ ] Update a package version.
- [ ] Update a language version.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

Rename the following repositories:

- *amedium/auth* `->` **alxmedium/auth** 
- *amedium/app* `->` **alxmedium/webapp**
