### ISSUE TITLE
User Service

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#42]
# User Service

Create a new project to handle the users logic.

## Checklist

- [ ] The feature breaks the existing code base.
- [ ] Update a package version.
- [ ] Update a language version.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

Create a new project to solve the initial requests of the [auth-service](https://github.com/alxmedium/auth-service)
