### ISSUE TITLE
Update CircleCI Configuration

### ISSUE THREAD

**Issue by AlexisNava** [alxmedium/alxmedium#9]
# Update CircleCI Configuration

Update **CircleCI** configuration for the repositories with previously configured.

## Checklist

- [x] The feature breaks the existing code base.
- [ ] Update a package version.
- [ ] Update a language version.
- [ ] It is related to an opened issue(please mentioned below).

## Proposed Solution

Update the **CircleCI** configuration of the following projects:

- [auth](https://github.com/alxmedium/auth)
- [webapp](https://github.com/alxmedium/webapp)
